# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-hello-world

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10

# The `functions` block defines what code to deploy
functions:
  getAsset:
    handler: handler.getAsset
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: asset/{id}
          method: get
          cors: true
  createAsset:
    handler: handler.createAsset
    events:
      - http:
          path: asset
          method: post
          cors: true
  updateAsset:
    handler: handler.updateAsset
    events:
      - http:
          path: asset/{id}
          method: put
          cors: true
  deleteAsset:
    handler: handler.deleteAsset
    events:
      - http:
          path: asset/{id}
          method: delete
          cors: true